# permissions to do edit executionhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: executionhook-editor-role
rules:
- apiGroups:
  - apps.k8s.io
  resources:
  - executionhook
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.io
  resources:
  - executionhook/status
  verbs:
  - get
  - patch
  - update
