# permissions to do edit hookactions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hookaction-editor-role
rules:
- apiGroups:
  - apps.k8s.io
  resources:
  - hookactions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.io
  resources:
  - hookactions/status
  verbs:
  - get
  - patch
  - update
